[package]
name = "ideal_wordle_player"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.16.0"
ordered-float = "5.0.0"
rayon = "1.10.0"
tokio = { version = "1.44.1", features = ["full"] }
