[package]
name = "ideal_wordle_player"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
loading_bar = "1.1.0"
num_cpus = "1.16.0"
ordered-float = "5.0.0"
rand = "0.9.0"
tokio = { version = "1.44.1", features = ["full"] }
